language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: vOdp2M3QSqBT+dz9VYsqTZ+iH0+c/sGxUre6bfVENdJuetZA8RxojbXJ8nv5ADJv690/zndZ2IttO/MY565cDIxuTiv0Te+bSy5JyvO4N2rAdEqpzKEQ33ZtOToiMgoMl91EkqPFOWqT8uLbo3q38LvYSFsioGSUAy0O1KsUdBb8JQBYtQ3jd0DoQu1Utghs/b7N34JIhXC0IFAaXlgb9JKDmpSPVtkL3RUFWO8QVP2rNJhk4Zxa9quEIykWh7p1YA3S66JFIX/kbTOsTKckjZZr3hA6qMjOPJP6mbFh6g6Ix8W9CMYDkjLS+9/efK8cpW2NEIjy5R+SWHs1hcJlP9hfLOUPFmu1VdVwT4/AqAqqq0QdtFKf0/XTsxsEnRQEA7QdvcJuGwWpX8T1ba3UNmlPp07nBmToaikOwAUueD4ZxaY+oeGCyKOS47hnG44IBpU0QBqny64GRonZVEtForkywdy4oHp2VtBTletrY4EbC26iseWrnKE+Y/W7gcXwolHOrC6YrdSQLEqxd4wMYG4VT0kiVM9odshTpKGNvNo+FWDlfmYQpNnqUtIdTzKGEGDweK2yiSYn4Iqtt8qobCDmRWgqjr1VW7MRguxDaMPSOxerF/muqQfTkfftxuPgXLJX3akNhDwXdxMC33lqFCgbRkLEtqFqGfks3E62rHA=
  app: my-blog-app-06