language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: tqYkZpVrmOdd0dd+gvC/C6el4ueJrh56diwtH/QUoNlfLLT8wFtBJByz17vHIkN65aixnsdsohwEyQKMAIS/OHlQA3sx+veX2iODhyLnlZo+i3n5eqCAF9Y32ZNcn9189tnKAJo4ldVpfnmFncnf7IEQ2dqWfBFsGcfsU+a8UvcSPEerP3qzjFigu25jleUHJvu7H1ERBMDG/VzEWKIzQnVRwzN3ulgxCzCXAp3HUmvM8OcuMSteRWBHE6Y+N4Z5nGM7MU2XTTIaJXhO5b96vx6taq4GvuEavLqwoyjw0AnLf7cV04wJ6kLC53Nr7RJuZvzbBcw3KToKd3S+dVvTWyONtl/luHJcJhtusgbYymoCXBPG7SfE7sH3g5MsJGVn5jO4tiNigyvOl2YIjGNuI00otXdn7bGZZB521gWDDosWyVRXa32vq/VrFKat1Bytqc5/7V5apRzpbp+g3S7lNCkmbfQ4QFXgnjMteKWuGAN3vSZtxrWHwyAU1R3hK5H6ls4bNhHdsPE1+MMk42YJ94+POO+kjdEM6gvXpI6enI6S3hLNZ7Xm345pThczaNn8U11LVYoBsUmn0FGXCD1I4OhVLcKow4jTYmqDQifW5hhRC43qZYAMV6NNjBMPOr0q7f0e3XhgwLEyparSyHxGq7U4/PU0KQ5tMUDT2cEUSzU=
    app: my-blog-app-06